### ISSUE TITLE
Problem: No overview on how gitbloq is intended to work

### ISSUE THREAD

**Issue by samuelralak** [Blockrazor/gitbloq#13]
Problem: There's no overview on how gitbloq is intended to work. This is needed as it should work as guide/direction in creating future issues

Solution: Ask @gazhayes to provide a brief yet comprehensive description of the Project - C4 style, possibly include it in README.md

cc: @gazhayes

**Comment by gsovereignty** [comment]
It's basically impossible to compare different blockchain projects' github activity at the moment. You have to manually search and see how active the community around the project really is. It's easy to see how active the *main* repo is, but not the community in general (using/building the related infrastructure and libraries etc).

So the idea with gitbloq is to harvest **all** meaningful data through the github API (and probably some scraping too since the API is a bit limited in terms of what data it can provide), and display it in a large variety of ways, maybe give users the ability to contrast and compare different aspects etc.

As with all C4 projects, we're really just starting with a problem and seeing what happens, so that obviously limits how much we can predict what this will end up looking like, but I think that probably gives you a pretty good idea (does it?)

**Comment by samuelralak** [comment]
@gazhayes yes sir, that's perfect
